apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result-brands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
      variant: brands
  template:
    metadata:
      labels:
        app: result
        variant: brands
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result
        name: result
        ports:
        - containerPort: 80
          name: result
        env:
        - name: OPTION_A
          value: "Garmin"
        - name: OPTION_B
          value: "Xiaomi"
