apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
      variant: brands
  template:
    metadata:
      labels:
        app: vote
        variant: brands
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: vote
        ports:
        - containerPort: 80
          name: vote
        env:
        - name: OPTION_A
          value: "Garmin"
        - name: OPTION_A
          value: "OPTION_B"
