apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote-pets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
      variant: pets
  template:
    metadata:
      labels:
        app: vote
        variant: pets
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: vote
        ports:
        - containerPort: 80
          name: vote
        env:
        - name: OPTION_A
          value: "Cat"
        - name: OPTION_B
          value: "Dog"